# Generated by Django 4.1 on 2022-08-24 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='cantidad_hijos',
            new_name='hijos',
        ),
    ]
